// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzxWq7d4E-H6mSYY4oC0CO4i9nxAHkhqY',
    appId: '1:1090623725456:web:2eeba54c0e6ba61d335d15',
    messagingSenderId: '1090623725456',
    projectId: 'realesae',
    authDomain: 'realesae.firebaseapp.com',
    storageBucket: 'realesae.appspot.com',
    measurementId: 'G-3PS38411YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFA_pX9Sb7TejaDgajMtJOiprecDgZXlI',
    appId: '1:1090623725456:android:6730173c811a859d335d15',
    messagingSenderId: '1090623725456',
    projectId: 'realesae',
    storageBucket: 'realesae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApKCQPMD8mMJPGSeJ_m2k3qFxonIZnUWs',
    appId: '1:1090623725456:ios:3755858c26345369335d15',
    messagingSenderId: '1090623725456',
    projectId: 'realesae',
    storageBucket: 'realesae.appspot.com',
    iosBundleId: 'com.example.realEsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApKCQPMD8mMJPGSeJ_m2k3qFxonIZnUWs',
    appId: '1:1090623725456:ios:3755858c26345369335d15',
    messagingSenderId: '1090623725456',
    projectId: 'realesae',
    storageBucket: 'realesae.appspot.com',
    iosBundleId: 'com.example.realEsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzxWq7d4E-H6mSYY4oC0CO4i9nxAHkhqY',
    appId: '1:1090623725456:web:b3560264f6326ef6335d15',
    messagingSenderId: '1090623725456',
    projectId: 'realesae',
    authDomain: 'realesae.firebaseapp.com',
    storageBucket: 'realesae.appspot.com',
    measurementId: 'G-58JKED1P6E',
  );
}
